language:
  - ruby
rvm:
  - 2.2.0
  - 2.6.3
  - ruby-head
gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
